### ISSUE TITLE
License

### ISSUE THREAD

**Issue by waltercool** [parazyd/cancel#3]
Seems like the project is missing a license.

I would suggest using the Hippocratic license, looks nice and was made by the greatest Coraline Ada.

https://firstdonoharm.dev/version/2/1/license.html

**Comment by parazyd** [comment]
Is this a free software license?

**Comment by waltercool** [comment]
It's free software, but the rights to use are up to you. The license grants the owner right to revoke access to users you may not like.

**Comment by parazyd** [comment]
>This license is not GPL-compatible, because it restricts FSF's freedom 0, the freedom to use the software for any purpose. This freedom is protected in section 2 of GPL v3:

Cancelled!
