### ISSUE TITLE
Can I cancel this repo? 

### ISSUE THREAD

**Issue by fsvk74** [parazyd/cancel#5]
Can I cancel this repo?

**Comment by fsvk74** [comment]
And Windows 10 or my test repo?

**Comment by parazyd** [comment]
What do you mean by adding Windows 10 or your test repo?

**Comment by fsvk74** [comment]
My private repo has 2 iso of windows 10 ltsb by lex6000: 1607 and 1809 (If my I will need windows, I just clone repo and write iso on USB

**Comment by fsvk74** [comment]
I saved it for me only.

**Comment by fsvk74** [comment]
And, I have Windows 10 DVD (Official), and I don't need this repo now.

**Comment by fsvk74** [comment]
Can I cancel it with your program?

**Comment by fsvk74** [comment]
![BkfFpfnowWQ](https://user-images.githubusercontent.com/60939957/112753876-2620d980-8fe2-11eb-84d2-e52ab592d710.jpg)
My DVD's (I got it on my birthday)

**Comment by fsvk74** [comment]
Admins of github removed my repo) Thanks!
